name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: true
        
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Test build website
        env:
          GITHUB_PAT: ${{ secrets.DOCUSAURUS_GITHUB_PAT }}
          GHE_PAT: ${{ secrets.DOCUSAURUS_GHE_PAT }}
          GHE_API_URL: ${{ secrets.DOCUSAURUS_GHE_API_URL }}
        run: pnpm build
